### ISSUE TITLE
大佬，我用的这个代码，没有实现，能否加个微信，给你看下图片

### ISSUE THREAD

**Issue by IOCloudFly** [wilin52/vertical_text#1]
我在做个古诗词，结果就一行，没有换行，不清楚什么原因导致的

**Comment by IOCloudFly** [comment]
大佬，我想做个需求，就是把一句话，分段，遇到逗号，问好，句号，就给给替换成换行，我想请教你一下代码该怎么写

**Comment by wilin52** [comment]
> 大佬，我想做个需求，就是把一句话，分段，遇到逗号，问好，句号，就给给替换成换行，我想请教你一下代码该怎么写
你可以修改'vertival_text.dart',  按照你的条件，newLine = true 就好了

**Comment by wilin52** [comment]
请问，问题是否解决，如果解决，我就将issue 关闭
