### ISSUE TITLE
你好，当前方向：从上到下、从右到左，能否实现：从上到下、从左到右呢？

### ISSUE THREAD

**Issue by eaoriqileng** [wilin52/vertical_text#2]
你好，当前方向：从上到下、从右到左，能否实现：从上到下、从左到右呢？

**Comment by wilin52** [comment]
> 你好，当前方向：从上到下、从右到左，能否实现：从上到下、从左到右呢？

这个应该是很好做的，可以看源码，x轴从0开始， 当y 轴已经不够画一个文字的时候，x 增加。

**Comment by eaoriqileng** [comment]
好的，谢谢。

**Comment by wilin52** [comment]
> 好的，谢谢。
不客气，你试试？

![image](https://user-images.githubusercontent.com/9528566/72237998-64b5b880-3617-11ea-8195-6013e5e89d00.png)
